- platform: mqtt
  name: "Office Ceiling Light"
  state_topic: "stat/officelight/POWER"
  command_topic: "cmnd/officelight/POWER"
  availability_topic: "tele/officelight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Office Desk Light"
  state_topic: "stat/officelight-desk/POWER"
  command_topic: "cmnd/officelight-desk/POWER"
  availability_topic: "tele/officelight-desk/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
 
- platform: mqtt
  name: "Office Lego Light"
  state_topic: "stat/ledlight/POWER"
  command_topic: "cmnd/ledlight/POWER"
  qos: 1
  retain: true
  payload_on: "ON"
  payload_off: "OFF"
  brightness_scale: 100
  brightness_command_topic: "cmnd/ledlight/DIMMER"
  brightness_state_topic: "stat/ledlight/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  rgb_command_topic: "cmnd/ledlight/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
  rgb_command_mode: RGB
  rgb_state_topic: "stat/ledlight/RESULT"
  rgb_value_template: "{{ value_json.Color[0:2] | int(base=16) }},{{ value_json.Color[2:4] | int(base=16) }},{{ value_json.Color[4:6] | int(base=16) }}"