- platform: broadlink
  name: Office TV
  host: broadlink
  mac: '34:ea:34:42:a6:b2'
  ircodes_ini: 'includes/media_player_ircodes/hisense_officeTv.ini'
  ping_host: chromecast-officetv
- platform: cast
  host: google-home
- platform: cast
  host: chromecast-maintv
- platform: cast
  host: chromecast-officetv