- platform: speedtest
  minute:
    - 0
    - 10
    - 20
    - 30
    - 40
    - 50
  monitored_conditions:
    - download
    - upload
    
- platform: dnsip
  hostname: ptorrezao.duckdns.org
  resolver: 8.8.8.8
